### PR TITLE
substitute after preprocessing

### LINKED ISSUE #27: Item substitution doesn’t respect shader defs
Conditionally importing the same item on different cases causes the wrong item to be substituted, as substitution happens before preprocessing. 

From nisevoid on discord:
Like this my shader works (if EFFECT_ID is 3)
```rust
#if EFFECT_ID == 3
    #import "shaders/skills/railgun_trail.wgsl" frag, vert
#endif
```
It still works now (still EFFECT_ID 3):
```rust
#if EFFECT_ID == 2
    #import "shaders/skills/slash.wgsl" frag, vert
#else if EFFECT_ID == 3
    #import "shaders/skills/railgun_trail.wgsl" frag, vert
#endif
```
But now it doesn't (still EFFECT_ID 3):
```rust
#if EFFECT_ID == 3
    #import "shaders/skills/railgun_trail.wgsl" frag, vert
#else if EFFECT_ID == 4
    #import "shaders/skills/magic_arrow.wgsl" frag, vert
#endif
```
It also doesn't if I use the second snippet and swap the ifs around. Same thing with separate if blocks instead of else ifs. Same thing happens on any other effect as long as another follows it, it'll say something along the lines of `missing import '"shaders/skills/railgun_trail.wgsl"'`. Same thing happens with non-local imports. It even breaks if I put an import after it that isn't in an if ... I'm not entirely sure what is even going wrong here 🤔

### PR DESCRIPTION
**Pull request by robtfm**
fixes #27

perform module and item substitution after preprocessing to make sure we use the right imports. 

this is a breaking change as we need to add shader defs into the public `ErrSource::Module` variant, so that errors can be reported with the correct substitutions.

### CODE REVIEW

File: src/compose/mod.rs [hunk 1]
```diff
@@ -1499,16 +1534,7 @@ impl Composer {
...
-            .sanitize_and_substitute_shader_string(source, &imports)
-            .map_err(|e| ComposerError {
-                inner: e,
-                source: ErrSource::Constructing {
-                    path: file_path.to_owned(),
-                    source: source.to_owned(),
-                    offset: 0,
-                },
-            })?;
+        let substituted_source = self.sanitize_and_set_auto_bindings(source);
```
Comment (cart) [inline src/compose/mod.rs:1537]: Is this being called twice (on the same `source` input) in the same function intentional?

Comment (robtfm) [reply src/compose/mod.rs]: nope, removed, thanks.

i had some trouble with CI failures that didn't occur locally, i believe due to github treatment of `\r`s, so i moved the sanitize call up to the start of the function and forgot to remove the original call.

**Review by cart — APPROVED** [review]
